version: '3.8'

services:
  apache:
    build: .
    expose:
      - "80"  # Доступ только внутри Docker-сети
    volumes:
      - ./src:/var/www/html
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    ports:
      - "5000:80"  # Публикуем порт наружу
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - apache
    networks:
      - app-network

networks:
  app-network:
    driver: bridge